<?php	

/**
 * This file has been generated by PhpUnitTestGenerator
 *
 * @copyright 2018 Stefano Bonvicini <stefano.bonvicini@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace ExeguibileDotIt\Kontrast\Colors;
use \PHPUnit\Framework\TestCase;



class ColorSpaceTest extends TestCase
{

    /**
     * @var ColorSpace instance of the class object
     */
    protected $object;

    /**
     * Sets up the fixture
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ColorSpace;
    }

    /**
     * Method defineColorSystem.
     *
     * @param ColorSystemBehaviour $cs
     *
     * @param string $label
     * 
     * @return self
     */
    public function testDefineColorSystem()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /** 
     * Method isValidLabel 
     *
     * @param string $label
     *
     * @return bool true if the $label string 
     * has a valid format
     **/
    public function testIsValidLabel()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /**
     * Method getSystemObject
     *
     * @param int $sysID identifier of the required color system
     * 
     * @throws \InvalidArgumentException
     * @throws \OutOfRangeException
     *
     * @return ColorSystemBehaviour
     */
    public function testGetSystemObject()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }


    public function testCount()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

}



