<?php	

/**
 * This file has been generated by PhpUnitTestGenerator
 *
 * @copyright 2018 Stefano Bonvicini <stefano.bonvicini@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace ExeguibileDotIt\Kontrast\Colors;
use \PHPUnit\Framework\TestCase;



class ColorTest extends TestCase
{

    /**
     * @var Color instance of the class object
     */
    protected $object;

    /**
     * Sets up the fixture
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Color;
    }

    /**
     * Method addColorSpaceSupport.
     *
     * @param ColorSpace $cs
     * 
     * @return void
     */
    public function testAddcolorspaceisupport()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /**
     * Method _call.
     *
     * 
     * @throws \RuntimeException
     *
     * @return mixed
     */
    public function test_call()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /**
     * Method __get.
     *
     * @param string $prop
     * 
     * @return mixed
     */
    public function test__get()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /**
     * Method __set.
     *
     * @param string $prop
     *
     * @param mixed $val
     * 
     * @return self
     */
    public function test__set()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /**
     * Method convertTo.
     *
     * @param int $sysID
     * 
     * @throws \RuntimeException
     *
     * @todo complete the logic
     *
     * @return self
     */
    public function testConvertto()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }


}



