<?php	

/**
 * This file has been generated by PhpUnitTestGenerator
 *
 * @copyright 2018 Stefano Bonvicini <stefano.bonvicini@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace ExeguibileDotIt\Kontrast\Colors;
use \PHPUnit\Framework\TestCase;



class ColorTest extends TestCase
{

    /**
     * Method setSupportedColorSystem.
     *
     * @param ColorSpace $cs
     * 
     * @return void
     */
    public function testSetSupportedColorSystem()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }


    /**
     * Method convertTo.
     *
     * @param int $sysID
     * 
     * @throws \RuntimeException
     *
     * @todo complete the logic
     *
     * @return self
     */
    public function testConvertTo()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

}



