<?php	

/**
 * This file has been generated by PhpUnitTestGenerator
 *
 * @copyright 2018 Stefano Bonvicini <stefano.bonvicini@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace ExeguibileDotIt\Kontrast\Colors;
use \PHPUnit\Framework\TestCase;



class HtmlColorTest extends TestCase
{

    /**
     * @var HtmlColor instance of the class object
     */
    protected $object;

    /**
     * Sets up the fixture
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HtmlColor;
    }

    /**
     * Method hexadecimal.
     *
     * @param string $v
     * 
     * @throws \InvalidArgumentException
     *
     * @return mixed self in setter mode hexadecimal string in getter mode
     * without #
     */
    public function testHexadecimal()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }


    public function testIsvalidhexadecimalcolor()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /**
     * Method __clone.
     * 
     * @return 
     */
    public function test__clone()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }

    /**
     * Method setUndefined
     *
     * @return self
     */
    public function testSetundefined()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }


    public function testIsundefined()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }


    public function test__tostring()
    {
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );

    }


}



