<?php	

/**
 * This file has been generated by PhpUnitTestGenerator
 *
 * @copyright 2018 Stefano Bonvicini <stefano.bonvicini@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace ExeguibileDotIt\Kontrast\Colors;
use \PHPUnit\Framework\TestCase;



class HtmlColorSystemTest extends TestCase
{

    /**
     * @var HtmlColorSystem instance of the class object
     */
    protected $object;

    /**
     * Sets up the fixture
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HtmlColorSystem;
    }

    /**
     * Method toRGB.
     *
     * @return RGBColor object
     */
    public function testToRGB()
    {

        $this->object->hexadecimal('aab1c3');

        $rgb = $this->object->toRGB();

        $this->assertEquals($rgb->r(), 170);

        $this->assertEquals($rgb->g(), 177);

        $this->assertEquals($rgb->b(), 195);

        return $rgb;

    }

    /**
     * Method fromRGB. Sets up object
     * params by RGBColor object in this case is like cloning an object. If
     * $color is not defined then no change is made
     *
     * @param RGBColor $color
     *
     * @return self
     *
     * @depends testToRGB
     */
    public function testFromRGB($rgb)
    {
        $this->object->fromRGB($rgb);

        $this->assertEquals('aab1c3', $this->object->hexadecimal());

    }

}



