<?php	

/**
 * This file has been generated by PhpUnitTestGenerator
 *
 * @copyright 2018 Stefano Bonvicini <stefano.bonvicini@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 */

namespace ExeguibileDotIt\Kontrast\Colors;
use \PHPUnit\Framework\TestCase;



class RGBColorSystemTest extends TestCase
{

    /**
     * @var RGBColorSystem instance of the class object
     */
    protected $object;

    /**
     * Sets up the fixture
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RGBColorSystem;
    }

    /**
     * Method toRGB.
     *
     * @return RGBColor object
     */
    public function testToRGB()
    {
        $this->object->r(33)->g(255)->b(3);

        $copy =$this->object->toRGB();

        $this->assertEquals($copy->r(), $this->object->r());

        $this->assertEquals($copy->g(), $this->object->g());

        $this->assertEquals($copy->b(), $this->object->b());

        return $copy;

    }

    /**
     * Method fromRGB. Sets up object
     * params by RGBColor object in this case 
     * is like cloning an object
     *
     * @param RGBColor $color
     *
     * @return self
     *
     * @depends testToRGB
     */
    public function testFromRGB(RGBColor $color)
    {

        $this->object->fromRGB($color);

        $this->assertEquals($color->r(), $this->object->r());

        $this->assertEquals($color->g(), $this->object->g());

        $this->assertEquals($color->b(), $this->object->b());

    }

}



